PUT http://localhost:8080/api/blog/5e362aeaafbc1c94cf23d795

{"blog_delta_content":"[{\"insert\":\"这篇博客主要就是为了进一步调试。这个编辑器的性能并没有想象中的按么令人满意，很多字体什么的都模拟不出来。\\n#include<stdio.h>\"},{\"attributes\":{\"code-block\":true},\"insert\":\"\\n\"},{\"insert\":\"int main(){\"},{\"attributes\":{\"code-block\":true},\"insert\":\"\\n\"},{\"insert\":\"  printf(\\\"hello world!\\\");\"},{\"attributes\":{\"code-block\":true},\"insert\":\"\\n\"},{\"insert\":\"  return 0;\"},{\"attributes\":{\"code-block\":true},\"insert\":\"\\n\"},{\"insert\":\"}\"},{\"attributes\":{\"code-block\":true},\"insert\":\"\\n\"},{\"insert\":\"ok ，代码结束。\\n这一行要居中。写写 博客挺有意思的。\"},{\"attributes\":{\"align\":\"center\"},\"insert\":\"\\n\"},{\"insert\":\"这一行也要居中。\"},{\"attributes\":{\"align\":\"center\"},\"insert\":\"\\n\"},{\"insert\":\"这一行用最大的字体作为标题。\"},{\"attributes\":{\"header\":1},\"insert\":\"\\n\"},{\"insert\":\"标题下的一个小小段落。\\n\"},{\"insert\":{\"image\":\"/api/nopiser/picture/5e362ad6afbc1c94cf23d793\"}},{\"insert\":\"\\n这是我的桌面壁纸。看起来蛮好看的吧？\\n\"}]"}
###