GET http://localhost:8080/api/ritin/article
Accept: application/json

###

GET http://localhost:8080/api/ritin/article/5e086c739aef3f8868738300
Accept: application/json

###

PUT http://localhost:8080/api/ritin/article/5e26f733f203dd931bce9ad1
Accept: application/json

{"Content":"what???thefackanother"}
###

POST http://localhost:8080/api/ritin/article
Accept: application/json

{"Content":"heolsadfasadsdf_another"}

###

GET http://localhost:8080/api/ritin/article/5e26f707f203dd931bce9ad0
Accept: application/json

###

